name: Build

on:
  schedule:
    - cron: "0 12 * * SUN"
  push:
    branches:
      - master
  pull_request_target:
    branches: [ master ]


jobs:    
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.6', '3.9', '3.10']
        os: [ubuntu-latest, macos-latest]
    environment:
      name: random word ci
    steps:
      - name: Print Directory Structure of random_word_numpy
        run: ls -la random_word_numpy

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install packages
        run: |
            pip install pipenv
            pip install autopep8
            pip install pytest
            pipenv install
            pipenv run python setup.py install
      
      - name: Python Lint
        run: |
          make lint

      - name: Run tests
        run: |
          pipenv run pytest
